### ISSUE TITLE
Background bug after the last update.

### ISSUE THREAD

**Issue by HarutoSama** [loftyshaky/clear-new-tab#12]
a issue where each tap that is opened overwrites the background in other windows.

**Comment by loftyshaky** [comment]
If you use slideshow 1 millisecond options it's intended behavior.

**Comment by loftyshaky** [comment]
I managed to reproduce this bug once and only in one tab. But other tabs worked as expected (background should update in tabs only if slideshow is on). I will debug it when I find free time.

**Comment by HarutoSama** [comment]
I found an older version of your extension, which solved my problem.
I'll check out your updates, but for now I'm happy :)
